services:
  app:
    container_name: node_app
    image: nextjs-docker:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../../../docker/.env.docker
    environment:
      NODE_ENV: "production"
      PORT: "3000"
      HOSTNAME: "0.0.0.0"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/healthcheck', res => process.exit(res.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s