services:
  app:
    container_name: node_app
    image: nextjs-docker:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../../../docker/.env.docker
    environment:
      NODE_ENV: "production"
      PORT: "3000"
      HOSTNAME: "0.0.0.0"